TRUTH = (
    "Have you ghosted someone?"
    "Have you ever walked in on your parents doing 'it'?",
    "Who was the last person you liked the most? Why?",
    "Have you ever been suspended from school?",
    "If you had to choose between going naked or having your thoughts appear in thought bubbles above your head for everyone to read, which would you choose?",
    "What’s the one thing you’re afraid to lose?",
    "Do you like someone as of the moment?",
    "One thing about your best friend you are jealous of?",
    "Would you cheat on your boyfriend for a rich guy?",
    "What is your biggest turn on?",
    "When’s the last time you lied to your parents and why?",
    "Describe your ideal partner.",
    "What’s the scariest thing you’ve ever done?",
    "Have you ever picked your nose and eaten it?",
    "When’s the last time you lied to your parents and why?",
    "Have you ever lied about your age to participate in a contest?",
    "Have you ever been caught checking someone out?",
    "How many Saas-Bahu ke Serials You watched.",
    "Name the person who is special for you.",
    "Have u ever cried watching a movie or series? If yes then say which one?",
    "Have u ever Mischieved in School?",
    "Say one of your prank which you done and nobody Knows about it?",
    "How many Youtube Channels do you Had subscribed?",
    "Who is your Favourite Rapper",
    "Which anime Do You Like the most",
    "How many Times you failed in test or Exams",
    "Do You like someone who is presented here",
    "Who is the proest person which you ever meet",
    "What is life according to you?",
    "How many Times you revealed Secrets of your family and Friends",
    "What is your Favourite Food",
    "Who is your favourite Singer",
    "Which is your Favourite Religional Film",
    "What is love according to you",
    "Do you have a YouTube Channel",
    "Did you support the campaign Youth Against Rape",
    "Which is the dangerous experience in your life",
    "What is your Favourite Lifestyle program",
    "Which Family Member do you love the most",
    "Suggest me some more truths",
    "Who is your waifu?",
    "How many Times You are scolded by your teacher?",
    "Who is your Favourite Youtuber",
    "Do you know about anime",
    "Which is your Favourite Book",
    "Have you ghosted anybody",
    "Do you believe in Ghosts",
    "What are your future plans",
    "Say something about your carrier",
    "Which actor/actress do you like the most",
    "Which anime movie/series made you cry",
    "Which comedy show/anime do you like the most.",
    "Do you seen TikTok?",
    "Are You a TikToker?",
    "What will be your Reaction when TikTok is banned?",
    "To whom you said I Love You?",
    "What is your future goal?",
    "Which qualities do you want from your life partner",
    "Do you Like BTS",
    "Do you like Black-Pink",
    "Who is your Favourite BTS",
    "Who is your Favourite Rock Band",
    "What was the last thing you searched for on your phone?",
    "Have you ever got caught by cheating at exam hall?",
    "Who do you hate the most?",
    "How many kids do you want to have in the future?",
    "Would you date someone shorter than you?",
    "If someone paid you $1000 to wear your bra outside your shirt, would you do it?",
    "Have you ever fapped if you've done then tell when you have done last time?",
    "If your crush told you he liked your best friend, what would you do?",
    "Would you ditch your friends if you could become the most popular girl in school?",
    "Have you ever had a crush on a teacher? Who?",
    "What's the most embarrassing thing you've ever done in front of a teacher?",
    "Have you ever stuck gum under a desk?",
    "Have u ever get caught during intimate scenes in anime?",
    "Ever search hentai on YouTube?",
    "Ever watched gay hentai?",
    "Ever sent the link of hentai to ur teacher?",
    "What's the worst class to have first period?",
    "If you had to delete one app from your phone, which one would it be?",
    "Have you ever peed on the side of the road?",
    "What’s the dumbest thing you’ve done to impress a crush?",
    "If you could get surgery to look like any celebrity, who would it be?",
    "Have you ever pretended to like a gift you hated and what did you do with it?",
    "How old were you when you found out how babies are made?",
    "Have you ever chew gutka or paan masala if yes then tell when was the last time?",
    "If you could go on a date with any celebrity, who would it be?",
    "Congratulations 🎉🎉, Don't do any truth this Time. Enjoy ;)",
    "Have your ever lied that you never cheated on exam?",

)

DARE = (
    "Show the most embarrassing photo on your phone"
    "Show the last five people you texted and what the messages said",
    "Let the rest of the group DM someone from your Instagram account",
    "Eat a raw piece of garlic",
    "Do 100 squats",
    "Keep three ice cubes in your mouth until they melt",
    "Say something dirty to the person on your leftYou've got company!",
    "Give a foot massage to the person on your right",
    "Put 10 different available liquids into a cup and drink it",
    "*Yell out the first word that comes to your mind",
    "Give a lap dance to someone of your choice",
    "Remove four items of clothing",
    "Like the first 15 posts on your Facebook newsfeed",
    "Eat a spoonful of mustard",
    "Keep your eyes closed until it's your go again",
    "Send a sext to the last person in your phonebook",
    "Show off your orgasm face",
    "Seductively eat a banana",
    "Empty out your wallet/purse and show everyone what's inside",
    "Do your best sexy crawl",
    "Pretend to be the person to your right for 10 minutes",
    "Eat a snack without using your hands",
    "Say two honest things about everyone else in the group",
    "Twerk for a minute",
    "Try and make the group laugh as quickly as possible",
    "Try to put your whole fist in your mouth",
    "Tell everyone an embarrassing story about yourself",
    "Try to lick your elbow",
    "Post the oldest selfie on your phone on Instagram Stories",
    "Tell the saddest story you know",
    "Howl like a wolf for two minutes",
    "Dance without music for two minutes",
    "Pole dance with an imaginary pole",
    "Let someone else tickle you and try not to laugh",
    "Put as many snacks into your mouth at once as you can",
    "Send your most recent selfie.",
    "Send your ugliest selfie.",
    "Send a screenshot of your facebook search history",
    "Send a screenshot of your gallery.",
    "Send a screenshot of your messenger inbox",
    "Tell something very intimate.",
    "Send a screenshot of your twitter inbox",
    "Send a screenshot of your homescreen.",
    "Send a cover of your favorite song. 🎤",
    "Do a lyric prank on someone and send proof.",
    "Confess to your current crush. ❤️",
    "Declare who is your true love.",
    "Send a screenshot of your gallery.",
    "Set your crush’s picture as your dp.",
    "Suggest me more dares.",
    "See a hentai😏",
    "Complete peaky Blinders in 2 days",
    "Send the screenshot of your Instagram Posts",
    "Send the screenshot of Your YouTube Channel",
    "Watch and compelete Boku no pico 🙃",
    "Say I love you to your mother/father😄",
    "For this dare do this : GO TO YOUTUBE ----> SEARCH DHINCHAK POOJA ----> SELECT THIS SONG SELPHIE MAINE LELI AND HEAR THAT FULL",
    "Send your beautiful photo",
    "Buy soda shake it then tell a friend to open it",
    "Send the photo of your favourite r-rated series",
    "Give the flower sticker/emoji to your crush present here",
    "Send Image of your favourite Youtuber",
    "Send anyone TikTok video",
    "Send your cringe video",
    "Sing your favourite song in VC",
    "Drop your all anime and Start watching One Piece/Detective Conan",
    "Send photo of your school/collage",
    "Mix 5 Different Drinks and drink it",
    "Do a prank with anyone present Here",
    "Recommand Anime to a non-anime Watcher",
    "Dressed as a Cosplay.",
    "Tease your best friend",
    "Make a tatoo on your hand",
    "Say your Favourite Dialogue", 
    "Send ss of your tachiyomi search history?",
    "Give a screenshot of talking to the girl in What'sapp.?
    "Send crush your ugliest photo?",
    "Send message to your teacher",
    "Confess ur crush then block her before getting reply",
    "Send your browsing history to your crush",
    "Flirt with a member of the group that is of the same sex as you.",
    "Dance for one minute without any music. And Send that video",
    "Dress as female and send screen shot in group",
    "Send your call history",
    "Send hi to your teacher",
    "Send your photo in your current pose",
    "Speak 'Mai nashedi hu bahut bada' in VC or Voice message",
    "Send your photo in school GRP. Than delete it",
    "Send your SS of Instagram dm",
    "Congratulations 🎉🎉, Don't do any dare this Time. Now another person's Chance",
    "Send your SS of last person that you have texted",
)
